export default {
  serverURL: 'https://vitumob.com',
  merchants: [
    'amazon.co.uk',
    'amazon.com',
    'apple.com',
    // 'autopartswarehouse.com',
    'bathandbodyworks.com',
    'bestbuy.com',
    'cookieskids.com',
    'ebay.com',
    'everything5pounds.com',
    'forever21.com',
    'hm.com',
    'lessthan10pounds.com',
    'macys.com',
    'marksandspencer.com',
    'marksandspencerlondon.com',
    'target.com',
    'toysrus.com',
    'victoriassecret.com',
    'walgreens.com',
    'walmart.com',
    'zara.com',
    'zulily.com',
  ],
};
