export default {
  serverURL: 'https://vitumob.com',
  merchants: [
    'amazon.co.uk', 'amazon.com',
    'apple.com',
    // 'aritzia.com',
    'armaniexchange.com',
    'autopartswarehouse.com',
    'barneys.com',
    'bathandbodyworks.com',
    // 'beauty.com', 'drugstore.com', => closed down redirect to walgreens
    'bestbuy.com',
    // 'cabelas.com',
    'cellhut.com',
    // 'childrensplace.com',
    'cookieskids.com',
    'davidsbridal.com',
    // 'debenhams.com',
    'ebay.com',
    // 'etaeproducts.com',
    'everything5pounds.com',
    'familychristian.com',
    'forever21.com',
    'hm.com',
    'lessthan10pounds.com',
    'macys.com',
    'marksandspencer.com', 'marksandspencerlondon.com',
    // 'missguidedus.com',
    'motherhood.com',
    'neimanmarcus.com',
    'newegg.com',
    'nordstrom.com',
    // 'roguefitness.com',
    // 'samsbeauty.com',
    'target.com',
    'toysrus.com',
    'victoriassecret.com',
    'walgreens.com',
    'walmart.com',
    // 'worldrugbyshop.com',
    // 'worldsoccershop.com',
    'zara.com',
    // 'zulily.com',
  ],
};
